<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title ?? 'Document' }}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            margin: 40px;
            color: #2d3748;
        }
        
        h1 {
            color: #1a202c;
            border-bottom: 2px solid #4299e1;
            padding-bottom: 10px;
        }
        
        .content {
            margin-top: 20px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        
        th, td {
            border: 1px solid #e2e8f0;
            padding: 12px;
            text-align: left;
        }
        
        th {
            background: #edf2f7;
            font-weight: 600;
        }
        
        tr:nth-child(even) {
            background: #f7fafc;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            font-size: 12px;
            color: #718096;
        }
    </style>
</head>
<body>
    <h1>{{ $title ?? 'Document' }}</h1>
    
    <div class="content">
        {!! $content ?? '<p>No content provided.</p>' !!}
    </div>
    
    <div class="footer">
        Generated by LaraPDFX | {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
